#!/usr/bin/env node
// Measures every style value in the mobile app and writes STYLE_MEASUREMENT.md.
//
//   node scripts/measure-styles.mjs
//
// Why this exists: the design standard's vocabulary was derived from three
// reference screens and then patched five times as each newly migrated screen
// exposed a gap it did not cover. Three screens correctly answer "what does
// good look like". They cannot answer "how many roles does this app need" —
// and treating them as if they could produced repeated rework.
//
// This measures the population instead of a sample, so the vocabulary can be
// decided once against real counts. It reads only; it changes no app code.
//
// Style names are classified into jobs by a name heuristic, which is rough —
// `title` on a card and `title` on a screen land in the same bucket. The buckets
// are for orientation; the per-value examples are what to reason from.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "apps", "mobile", "src");
const OUT = join(ROOT, "STYLE_MEASUREMENT.md");

function walk(dir, out = []) {
  for (const n of readdirSync(dir)) {
    const p = join(dir, n);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (n.endsWith(".tsx")) out.push(p);
  }
  return out;
}

/** Rough job buckets from the style key. First match wins, so order matters. */
const JOBS = [
  [/^(page|screen)/i, "page title"],
  [/^(modal|sheet)/i, "modal title"],
  [/(section)/i, "section label"],
  [/(hero)/i, "hero title"],
  [/(price|amount|fee|total|value|num|count|score|rating)/i, "value"],
  [/(btn|button|cta|action|submit|apply|confirm|cancel)/i, "action"],
  [/(badge|chip|pill|tag|status)/i, "chip / badge"],
  [/(name|title|heading)/i, "title / name"],
  [/(label)/i, "label"],
  [/(sub|desc|body|meta|caption|hint|note|preview|empty|placeholder|text)/i, "body / meta"],
];

function jobOf(key) {
  for (const [re, job] of JOBS) if (re.test(key)) return job;
  return "other";
}

const files = walk(SRC);
const type = new Map();   // "size/weight" -> {count, job -> n, examples[]}
const radius = new Map(); // value -> {count, examples[]}
const space = new Map();  // value -> count
let migratedFiles = 0;
let styledFiles = 0;

const styleObj = /([A-Za-z_]\w*)\s*:\s*\{([^{}]*)\}/g;

for (const p of files) {
  const body = readFileSync(p, "utf8");
  if (!/fontSize|borderRadius/.test(body)) continue;
  styledFiles += 1;
  if (/from ['"]@shared\/tokens['"]/.test(body)) migratedFiles += 1;
  const short = relative(SRC, p).replace(/\\/g, "/").replace(/\.tsx$/, "");

  for (const m of body.matchAll(styleObj)) {
    const key = m[1];
    const props = m[2];

    const fs = /fontSize:\s*(\d+)/.exec(props);
    if (fs) {
      const w = /fontWeight:\s*'(\d+)'/.exec(props);
      const ls = /letterSpacing:\s*(-?[\d.]+)/.exec(props);
      const id = `${fs[1]}/${w ? w[1] : "-"}${ls ? ` ls${ls[1]}` : ""}`;
      const e = type.get(id) ?? { count: 0, jobs: new Map(), examples: [] };
      e.count += 1;
      const job = jobOf(key);
      e.jobs.set(job, (e.jobs.get(job) ?? 0) + 1);
      if (e.examples.length < 4) e.examples.push(`${short}.${key}`);
      type.set(id, e);
    }

    const br = /borderRadius:\s*(\d+)/.exec(props);
    if (br) {
      const e = radius.get(+br[1]) ?? { count: 0, examples: [] };
      e.count += 1;
      if (e.examples.length < 4) e.examples.push(`${short}.${key}`);
      radius.set(+br[1], e);
    }

    for (const sm of props.matchAll(/(?:padding|margin|gap)\w*:\s*(\d+)/g)) {
      space.set(+sm[1], (space.get(+sm[1]) ?? 0) + 1);
    }
  }
}

// ── report ──────────────────────────────────────────────────────────────────

const L = [];
L.push("# Style Measurement");
L.push("");
L.push("Generated by `node scripts/measure-styles.mjs`. Read-only; changes no app code.");
L.push("");
L.push(
  `Every raw style value in \`apps/mobile/src\` — **${styledFiles} files** carry a ` +
    `\`fontSize\` or \`borderRadius\`, of which **${migratedFiles}** already import ` +
    `\`@shared/tokens\`. Values below are the **unmigrated remainder plus anything ` +
    `still written as a literal**, which is what a vocabulary decision has to cover.`,
);
L.push("");
L.push(
  "The design standard's roles were derived from three reference screens. Those " +
    "screens answer what good looks like; they cannot answer how many roles the app " +
    "needs. This is the population, so that question can be settled once.",
);
L.push("");
L.push("---");
L.push("");

const typeRows = [...type.entries()].sort((a, b) => b[1].count - a[1].count);
const typeTotal = typeRows.reduce((n, [, e]) => n + e.count, 0);

L.push(`## Type — ${typeTotal} literal values, ${typeRows.length} distinct combinations`);
L.push("");
L.push("| size/weight | uses | dominant job | examples |");
L.push("| --- | ---: | --- | --- |");
for (const [id, e] of typeRows) {
  const job = [...e.jobs.entries()].sort((a, b) => b[1] - a[1])[0];
  L.push(`| \`${id}\` | ${e.count} | ${job[0]} (${job[1]}) | ${e.examples.slice(0, 2).join(", ")} |`);
}
L.push("");

// per-job breakdown
const byJob = new Map();
for (const [id, e] of type) {
  for (const [job, n] of e.jobs) {
    const m = byJob.get(job) ?? new Map();
    m.set(id, (m.get(id) ?? 0) + n);
    byJob.set(job, m);
  }
}
L.push("## Type by job");
L.push("");
L.push("The heuristic is the style's name, so it is rough — but a job whose values");
L.push("cluster tightly needs one role, and a job spread across ten needs a decision.");
L.push("");
for (const [job, m] of [...byJob.entries()].sort((a, b) => {
  const s = (x) => [...x[1].values()].reduce((p, c) => p + c, 0);
  return s(b) - s(a);
})) {
  const rows = [...m.entries()].sort((a, b) => b[1] - a[1]);
  const total = rows.reduce((n, r) => n + r[1], 0);
  L.push(`**${job}** — ${total} uses across ${rows.length} values`);
  L.push("");
  L.push("> " + rows.map(([id, n]) => `\`${id}\` ×${n}`).join(" · "));
  L.push("");
}

L.push("---");
L.push("");
const radRows = [...radius.entries()].sort((a, b) => b[1].count - a[1].count);
const radTotal = radRows.reduce((n, [, e]) => n + e.count, 0);
L.push(`## Radius — ${radTotal} literal values, ${radRows.length} distinct`);
L.push("");
L.push("| px | uses | examples |");
L.push("| ---: | ---: | --- |");
for (const [v, e] of radRows) L.push(`| ${v} | ${e.count} | ${e.examples.slice(0, 3).join(", ")} |`);
L.push("");

L.push("---");
L.push("");
const spRows = [...space.entries()].sort((a, b) => b[1] - a[1]);
const spTotal = spRows.reduce((n, r) => n + r[1], 0);
L.push(`## Spacing — ${spTotal} literal padding / margin / gap values`);
L.push("");
L.push("| px | uses |");
L.push("| ---: | ---: |");
for (const [v, n] of spRows.slice(0, 25)) L.push(`| ${v} | ${n} |`);
L.push("");

writeFileSync(OUT, L.join("\r\n"), "utf8");
console.log(
  `[measure-styles] wrote STYLE_MEASUREMENT.md — ${typeTotal} type values ` +
    `(${typeRows.length} combos), ${radTotal} radii (${radRows.length} distinct), ` +
    `${spTotal} spacing values`,
);
