import Image from "next/image";
import { cn } from "@/lib/utils";

// The Pickleball App wordmark.
//
// Replaces a CSS-drawn "CP / COMPETE PICKLEBALL" lockup that did not match the
// mobile app's brand at all — audit finding 3, "the two apps are not the same
// brand". The artwork is mobile's own `logo-splash.png`, so both platforms now
// ship the same mark rather than two interpretations of one.
//
// ── Two files, not one, and not a CSS filter ─────────────────────────────────
//
// The wordmark is navy "pickleball" + gold "app". Navy on the dark theme's navy
// ground (#050A18) is invisible, so a dark variant is required. A filter cannot
// produce it: `invert()` would turn the gold blue, and `brightness(0) invert(1)`
// would flatten the whole mark to white and throw the gold away — which is the
// half of the logo that carries the brand colour.
//
// So the dark asset recolours only the navy to white and leaves the gold alone
// (generated by classifying pixels on b > r; see the commit that added it).
//
// The swap is CSS, not JavaScript: reading the theme in JS means the wrong logo
// renders for one frame on every load. `dark:` here resolves through the
// `@custom-variant dark (&:where(.dark, .dark *))` declared in globals.css, so
// it follows the existing next-themes toggle with no extra wiring.
//
// Only the light asset carries alt text — the dark one is aria-hidden, or a
// screen reader announces the name twice since both are always in the DOM.

const INTRINSIC = { width: 780, height: 134 } as const;

export function Logo({ className }: { className?: string }) {
  return (
    <span
      className={cn("inline-flex items-center shrink-0", className)}
      data-testid="dbpb-logo"
    >
      <Image
        src="/brand/logo-pickleball-app.png"
        alt="Pickleball App"
        {...INTRINSIC}
        priority
        className="h-7 w-auto sm:h-8 dark:hidden"
      />
      <Image
        src="/brand/logo-pickleball-app-dark.png"
        alt=""
        aria-hidden
        {...INTRINSIC}
        priority
        className="hidden h-7 w-auto sm:h-8 dark:block"
      />
    </span>
  );
}
